[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
invest_in_sol = "3EdJ94TjbyqmZJartpZHHdavKtH5aXQdUS6RyiPzGrmE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
